### PR TITLE
Option "Enable Note" had no effect

### PR DESCRIPTION
**Pull request by pooshok**

### CODE REVIEW

**Comment by tobias-forkel** [comment]
Hi @pooshok 

Thanks for your pull request. I will review this quickly and merge asap.

Cheers

**Comment by tobias-forkel** [comment]
I will release 1.0.3 in few hours with a code cleanup and your patch.

**Comment by tobias-forkel** [comment]
1.0.3 released. Thanks @pooshok

**Comment by pooshok** [comment]
Thanks @tobias-forkel  for useful module :+1:

**Pull request merged**
